services:
  # Сервис с Telegram ботом
  - type: web
    name: beer-challenge-bot
    runtime: python
    plan: free
    region: frankfurt  # Выберите ближайший регион
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false  # Требуется настройка вручную
      - key: GROUP_CHAT_ID
        sync: false  # Требуется настройка вручную
      - key: AdminPass
        sync: false  # Пароль администратора, настраивается вручную
      - key: PORT
        value: 8080
    disk:
      name: beer-challenge-data
      mountPath: /app/database
      sizeGB: 1  # Минимальный размер для бесплатного плана
    healthCheckPath: /  # Проверка работоспособности HTTP-сервера
    numInstances: 1  # Гарантируем запуск только одного экземпляра 